# Generated by Django 3.0.6 on 2021-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='label',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
